// wshuai modify

package logger

import (
	"fmt"
	"io"
	"os"
	"runtime"
	"strings"
	"sync"
	"time"
)

// These flags define which text to prefix to each log entry generated by the Logger.
// Bits are or'ed together to control what's printed.
// There is no control over the order they appear (the order listed
// here) or the format they present (as described in the comments).
// The prefix is followed by a colon only when Llongfile or Lshortfile
// is specified.
// For example, flags Ldate | Ltime (or LstdFlags) produce,
//	2009/01/23 01:23:23 message
// while flags Ldate | Ltime | Lmicroseconds | Llongfile produce,
//	2009/01/23 01:23:23.123123 /a/b/c/d.go:23: message
const (
	Ldate         = 1 << iota     // the date in the local time zone: 2009/01/23
	Ltime                         // the time in the local time zone: 01:23:23
	Lmicroseconds                 // microsecond resolution: 01:23:23.123123.  assumes Ltime.
	Llongfile                     // full file name and line number: /a/b/c/d.go:23
	Lshortfile                    // final file name element and line number: d.go:23. overrides Llongfile
	LUTC                          // if Ldate or Ltime is set, use UTC rather than the local time zone
	LstdFlags     = Ldate | Ltime // initial values for the standard logger
)

var levelMap = map[string]int{
	"DEBUG": 1,
	"INFO":  2,
	"ERROR": 3,
}

// A Logger represents an active logging object that generates lines of
// output to an io.Writer. Each logging operation makes a single call to
// the Writer's Write method. A Logger can be used simultaneously from
// multiple goroutines; it guarantees to serialize access to the Writer.
type Logger struct {
	mu           sync.Mutex // ensures atomic writes; protects the following fields
	prefix       string     // prefix to write at beginning of each line
	flag         int        // properties
	out          io.Writer  // destination for output
	buf          []byte     // for accumulating text to write
	suffix       string     // log suffix modify by wshuai
	level        int        // log level modify by wshuai
	logFileWidth int        // log file name width modify by wshuai
}

// New creates a new Logger. The out variable sets the
// destination to which log data will be written.
// The prefix appears at the beginning of each generated log line.
// The flag argument defines the logging properties.
func new(out io.Writer, prefix string, flag int, suffix string) *Logger {
	return &Logger{out: out, prefix: prefix, flag: flag, suffix: suffix}
}

// SetOutput sets the output destination for the logger.
func (l *Logger) setOutput(w io.Writer) {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.out = w
}

var std = new(os.Stderr, "", LstdFlags, "")

// Cheap integer to fixed-width decimal ASCII. Give a negative width to avoid zero-padding.
func itoa(buf *[]byte, i int, wid int) {
	// Assemble decimal in reverse order.
	var b [20]byte
	bp := len(b) - 1
	for i >= 10 || wid > 1 {
		wid--
		q := i / 10
		b[bp] = byte('0' + i - q*10)
		bp--
		i = q
	}
	// i < 10
	b[bp] = byte('0' + i)
	*buf = append(*buf, b[bp:]...)
}

// formatHeader writes log header to buf in following order:
//   * l.prefix (if it's not blank),
//   * date and/or time (if corresponding flags are provided),
//   * file and line number (if corresponding flags are provided).
func (l *Logger) formatHeader(buf *[]byte, t time.Time, file string, line int) {
	*buf = append(*buf, l.prefix...)
	if l.flag&(Ldate|Ltime|Lmicroseconds) != 0 {
		if l.flag&LUTC != 0 {
			t = t.UTC()
		}
		if l.flag&Ldate != 0 {
			year, month, day := t.Date()
			*buf = append(*buf, '[')
			itoa(buf, year, 4)
			*buf = append(*buf, '-')
			itoa(buf, int(month), 2)
			*buf = append(*buf, '-')
			itoa(buf, day, 2)
			*buf = append(*buf, ']')
			*buf = append(*buf, ' ')
		}
		if l.flag&(Ltime|Lmicroseconds) != 0 {
			hour, min, sec := t.Clock()
			*buf = append(*buf, '[')
			itoa(buf, hour, 2)
			*buf = append(*buf, ':')
			itoa(buf, min, 2)
			*buf = append(*buf, ':')
			itoa(buf, sec, 2)
			if l.flag&Lmicroseconds != 0 {
				*buf = append(*buf, '.')
				itoa(buf, t.Nanosecond()/1e3, 6)
			}
			*buf = append(*buf, ']')
			*buf = append(*buf, ' ')
		}
	}
	if l.flag&(Lshortfile|Llongfile) != 0 {
		if l.flag&Lshortfile != 0 {
			short := file
			for i := len(file) - 1; i > 0; i-- {
				if file[i] == '/' {
					short = file[i+1:]
					break
				}
			}
			//file = short
			file = fmt.Sprintf("%*s", l.logFileWidth, short)
		}
		*buf = append(*buf, '[')
		*buf = append(*buf, file...)
		*buf = append(*buf, ':')
		itoa(buf, line, 4)
		*buf = append(*buf, ']')
		*buf = append(*buf, " "...)
	}

	if l.suffix != "" {
		*buf = append(*buf, '[')
		*buf = append(*buf, l.suffix...)
		*buf = append(*buf, ']')
		*buf = append(*buf, " "...)
	}

}

// Output writes the output for a logging event. The string s contains
// the text to print after the prefix specified by the flags of the
// Logger. A newline is appended if the last character of s is not
// already a newline. Calldepth is used to recover the PC and is
// provided for generality, although at the moment on all pre-defined
// paths it will be 2.
func (l *Logger) output(calldepth int, s string) error {
	now := time.Now() // get this early.
	var file string
	var line int
	l.mu.Lock()
	defer l.mu.Unlock()
	if l.flag&(Lshortfile|Llongfile) != 0 {
		// Release lock while getting caller info - it's expensive.
		l.mu.Unlock()
		var ok bool
		_, file, line, ok = runtime.Caller(calldepth)
		if !ok {
			file = "???"
			line = 0
		}
		l.mu.Lock()
	}
	l.buf = l.buf[:0]
	l.formatHeader(&l.buf, now, file, line)
	l.buf = append(l.buf, s...)
	if len(s) == 0 || s[len(s)-1] != '\n' {
		l.buf = append(l.buf, '\n')
	}
	_, err := l.out.Write(l.buf)
	return err
}

// Flags returns the output flags for the logger.
func (l *Logger) Flags() int {
	l.mu.Lock()
	defer l.mu.Unlock()
	return l.flag
}

// SetFlags sets the output flags for the logger.
func (l *Logger) SetFlags(flag int) {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.flag = flag
}

// Prefix returns the output prefix for the logger.
func (l *Logger) Prefix() string {
	l.mu.Lock()
	defer l.mu.Unlock()
	return l.prefix
}

// SetPrefix sets the output prefix for the logger.
func (l *Logger) SetPrefix(prefix string) {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.prefix = prefix
}

func (l *Logger) SetSuffix(suffix string) {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.suffix = suffix
}

func (l *Logger) Level() int {
	l.mu.Lock()
	defer l.mu.Unlock()
	return l.level
}

func (l *Logger) SetLevel(level string) {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.level = levelMap[level]
}

func (l *Logger) SetLogFileWidth(width int) {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.logFileWidth = width
}

// SetOutput sets the output destination for the standard logger.
func setOutput(w io.Writer) {
	std.mu.Lock()
	defer std.mu.Unlock()
	std.out = w
}

// Flags returns the output flags for the standard logger.
func Flags() int {
	return std.Flags()
}

// SetFlags sets the output flags for the standard logger.
func SetFlags(flag int) {
	std.SetFlags(flag)
}

// Prefix returns the output prefix for the standard logger.
func Prefix() string {
	return std.Prefix()
}

// SetPrefix sets the output prefix for the standard logger.
func SetPrefix(prefix string) {
	std.SetPrefix(prefix)
}

func SetSuffix(suffix string) {
	std.SetSuffix(suffix)
}

func Level() int {
	return std.Level()
}

func SetLevel(level string) {
	std.SetLevel(level)
}

func SetFile(file string) (*os.File, error) {
	fd, err := os.OpenFile(file, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0666)
	setOutput(fd)
	return fd, err
}

func SetLogFileWidth(width int) {
	std.SetLogFileWidth(width)
}

func println(format string, v ...interface{}) {
	pc, _, _, _ := runtime.Caller(1)
	funcNames := strings.Split(runtime.FuncForPC(pc).Name(), ".")
	funcName := funcNames[len(funcNames)-1]

	if levelMap[funcName] >= std.level {
		std.SetSuffix(fmt.Sprintf("%-5s", funcName))
		if v[0] != "" {
			std.output(3, fmt.Sprintf(format+"\n", v...))
		} else {
			std.output(3, fmt.Sprintln(format))
		}
		std.SetSuffix("")
	}
}

func INFO(format string, v ...interface{}) {
	println(format, fmt.Sprint(v...))
}

func DEBUG(format string, v ...interface{}) {
	println(format, fmt.Sprint(v...))
}

func ERROR(format string, v ...interface{}) {
	println(format, fmt.Sprint(v...))
}

/*
 * example
 *
 *
import (
	"logger"
)

func initLog(logFile string, logLevel string) {
	logger.SetFile(logFile)
	logger.SetLevel(logLevel)
	logger.SetLogFileWidth(16)
	logger.SetFlags(logger.LstdFlags | logger.Lmicroseconds | logger.Lshortfile)
}

func init() {
	logFile := "test.log"
	logLevel := "DEBUG"
	initLog(logFile, logLevel)
}

func main() {
	logger.DEBUG("this is test log [%s]", "debug")
	logger.INFO("this is test log [%s]", "info")
	logger.ERROR("this is test log [%s]", "error")
	logger.DEBUG("this is test log [%s]", "debug")
	logger.INFO("this is test log [%s]", "info")
	logger.ERROR("this is test log [%s]", "error")
}
*/

